"""empty message

Revision ID: 1a477840b7d1
Revises: 12d36db7fec5
Create Date: 2022-11-24 00:22:10.868571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a477840b7d1'
down_revision = '12d36db7fec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adminuser', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adminuser', sa.Column('address', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
